function plottrajectory(x,y)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 05-Apr-2017 04:35:18

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(x,y,'ZDataSource','','MarkerEdgeColor','none','MarkerSize',0.5,...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color',[0 0.431372553110123 0.788235306739807]);

% Create xlabel
xlabel('Range (km)','FontWeight','bold','FontSize',14);

% Create title
title('Trajectory','FontSize',24);

% Create ylabel
ylabel('Height (km)','FontWeight','bold','FontSize',14);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1600]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',...
    [0.972549021244049 0.972549021244049 0.972549021244049],'FontSize',12,...
    'XGrid','on','YGrid','on');
